name: Cultivate Software Ltd, Staff Handbook

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'gen.rb', 'Procfile', 'Rakefile', 'README.md']
redirects: true
baseurl: "/ukstaffhandbook"


defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "page"
